import * as stylex from '@stylexjs/stylex';
import { venueColors as palette } from './palette.stylex';

export const styles = stylex.create({
   root: {
      minHeight: '100dvh',
      backgroundColor: palette.canvas,
      color: palette.text,
      display: 'flex',
   },
   desktopNav: {
      width: '232px',
      minHeight: '100dvh',
      position: 'fixed',
      insetInlineStart: 0,
      top: 0,
      borderRight: `1px solid ${palette.border}`,
      backgroundColor: palette.canvas,
      padding: '28px 18px',
      display: 'flex',
      flexDirection: 'column',
      zIndex: 4,
      '@media (max-width: 900px)': {
         display: 'none',
      },
   },
   brandMark: {
      width: '44px',
      height: '44px',
      borderRadius: '14px',
      backgroundColor: palette.amber,
      color: palette.canvas,
      display: 'grid',
      placeItems: 'center',
      fontSize: '1.5rem',
      fontWeight: 900,
      margin: '0 10px 36px',
      boxShadow: '0 10px 28px rgba(242, 169, 80, 0.18)',
   },
   desktopNavItems: {
      display: 'flex',
      flexDirection: 'column',
      gap: '6px',
   },
   navButton: {
      minHeight: '48px',
      color: palette.muted,
      borderRadius: '12px',
      padding: '0 14px',
      display: 'flex',
      alignItems: 'center',
      gap: '14px',
      fontSize: '1rem',
      textAlign: 'left',
      ':hover': {
         color: palette.text,
         backgroundColor: palette.panel,
      },
   },
   navButtonActive: {
      color: palette.text,
      backgroundColor: palette.panelRaised,
   },
   profileButton: {
      width: '42px',
      height: '42px',
      borderRadius: '50%',
      backgroundColor: palette.burgundy,
      color: palette.text,
      fontWeight: 800,
      marginTop: 'auto',
      marginLeft: '12px',
   },
   content: {
      width: '100%',
      marginLeft: '232px',
      '@media (max-width: 900px)': {
         marginLeft: 0,
      },
   },
   mobileHeader: {
      height: '64px',
      display: 'none',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 18px',
      borderBottom: `1px solid ${palette.border}`,
      position: 'sticky',
      top: 0,
      backgroundColor: 'rgba(14, 13, 12, 0.94)',
      backdropFilter: 'blur(16px)',
      zIndex: 3,
      '@media (max-width: 900px)': {
         display: 'flex',
      },
   },
   mobileBrand: {
      fontSize: '1.35rem',
      fontWeight: 900,
      letterSpacing: '-0.04em',
   },
   headerActions: {
      display: 'flex',
      gap: '8px',
   },
   iconButton: {
      color: palette.text,
      minWidth: '36px',
      minHeight: '36px',
      display: 'grid',
      placeItems: 'center',
      borderRadius: '50%',
      ':hover': {
         backgroundColor: palette.panelRaised,
      },
   },
   venueBar: {
      minHeight: '76px',
      display: 'flex',
      alignItems: 'center',
      gap: '14px',
      padding: '14px clamp(18px, 4vw, 48px)',
      borderBottom: `1px solid ${palette.border}`,
      backgroundColor: palette.panel,
   },
   venueIcon: {
      width: '42px',
      height: '42px',
      display: 'grid',
      placeItems: 'center',
      borderRadius: '13px',
      backgroundColor: palette.amberSoft,
      color: palette.amber,
   },
   venueText: {
      display: 'flex',
      flexDirection: 'column',
      gap: '2px',
   },
   eyebrow: {
      color: palette.muted,
      fontSize: '0.78rem',
      fontWeight: 700,
      textTransform: 'uppercase',
      letterSpacing: '0.08em',
   },
   venueName: {
      fontSize: '1rem',
   },
   checkinBadge: {
      marginLeft: 'auto',
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      color: palette.green,
      fontSize: '0.88rem',
      fontWeight: 700,
      padding: '8px 11px',
      borderRadius: '999px',
      backgroundColor: 'rgba(69, 185, 134, 0.1)',
      '@media (max-width: 460px)': {
         fontSize: 0,
      },
   },
   pageGrid: {
      maxWidth: '1060px',
      margin: '0 auto',
      padding: '30px clamp(16px, 4vw, 40px) 100px',
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 620px) 320px',
      gap: '40px',
      alignItems: 'start',
      '@media (max-width: 1120px)': {
         gridTemplateColumns: 'minmax(0, 620px)',
         justifyContent: 'center',
      },
      '@media (max-width: 640px)': {
         padding: '18px 0 90px',
      },
   },
   feedColumn: {
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: '18px',
   },
   stories: {
      display: 'flex',
      gap: '16px',
      overflowX: 'auto',
      padding: '2px 4px 8px',
      scrollbarWidth: 'none',
      '@media (max-width: 640px)': {
         padding: '0 16px 6px',
      },
   },
   story: {
      color: palette.text,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '6px',
      minWidth: '64px',
   },
   storyRing: {
      width: '62px',
      height: '62px',
      borderRadius: '50%',
      padding: '3px',
      background: `linear-gradient(145deg, ${palette.amber}, ${palette.burgundy})`,
   },
   storyLabel: {
      fontSize: '0.78rem',
      color: palette.muted,
      maxWidth: '70px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
   },
   avatar: {
      width: '46px',
      height: '46px',
      borderRadius: '50%',
      display: 'grid',
      placeItems: 'center',
      color: '#fff',
      fontWeight: 800,
      fontSize: '0.8rem',
      flexShrink: 0,
   },
   self: {
      width: '100%',
      height: '100%',
      backgroundColor: '#38322d',
      border: `3px solid ${palette.canvas}`,
   },
   plum: { backgroundColor: '#7c496c' },
   blue: { backgroundColor: '#3f668e' },
   green: { backgroundColor: '#34775f' },
   orange: { backgroundColor: '#a15b34' },
   post: {
      border: `1px solid ${palette.border}`,
      borderRadius: '18px',
      backgroundColor: palette.panel,
      overflow: 'hidden',
      '@media (max-width: 640px)': {
         borderInline: 'none',
         borderRadius: 0,
      },
   },
   postHeader: {
      minHeight: '68px',
      padding: '10px 14px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
   },
   postAuthor: {
      display: 'flex',
      alignItems: 'center',
      gap: '11px',
   },
   authorLine: {
      display: 'flex',
      alignItems: 'center',
      gap: '5px',
      color: palette.text,
   },
   postMeta: {
      color: palette.muted,
      fontSize: '0.8rem',
   },
   postImage: {
      position: 'relative',
      aspectRatio: '4 / 5',
      backgroundColor: palette.panelRaised,
   },
   image: { objectFit: 'cover' },
   livePill: {
      position: 'absolute',
      top: '14px',
      left: '14px',
      borderRadius: '999px',
      padding: '8px 11px',
      backgroundColor: 'rgba(14, 13, 12, 0.82)',
      color: palette.text,
      backdropFilter: 'blur(10px)',
      fontSize: '0.8rem',
      fontWeight: 700,
   },
   postBody: { padding: '10px 14px 16px' },
   postActions: {
      display: 'flex',
      justifyContent: 'space-between',
      marginBottom: '6px',
   },
   actionGroup: {
      display: 'flex',
      gap: '2px',
   },
   likeCount: {
      display: 'block',
      fontSize: '0.88rem',
      marginBottom: '7px',
   },
   caption: {
      color: palette.text,
      fontSize: '0.95rem',
      lineHeight: 1.5,
   },
   challengeButton: {
      marginTop: '14px',
      minHeight: '42px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '9px',
      width: '100%',
      borderRadius: '11px',
      color: palette.amber,
      backgroundColor: palette.amberSoft,
      fontWeight: 800,
      fontSize: '0.92rem',
   },
   sideColumn: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
      position: 'sticky',
      top: '104px',
      '@media (max-width: 1120px)': { display: 'none' },
   },
   sideCard: {
      backgroundColor: palette.panel,
      border: `1px solid ${palette.border}`,
      borderRadius: '18px',
      padding: '18px',
   },
   sectionHeading: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: '12px',
      marginBottom: '18px',
   },
   onlineCount: {
      color: palette.green,
      fontSize: '0.78rem',
      whiteSpace: 'nowrap',
   },
   peopleList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '14px',
   },
   personRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
   },
   personText: {
      minWidth: 0,
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      gap: '2px',
   },
   meetButton: {
      color: palette.amber,
      fontWeight: 800,
      fontSize: '0.85rem',
      padding: '8px',
   },
   primaryButton: {
      width: '100%',
      minHeight: '42px',
      borderRadius: '11px',
      backgroundColor: palette.amber,
      color: palette.canvas,
      fontSize: '0.92rem',
      fontWeight: 900,
      marginTop: '18px',
   },
   gameCard: {
      background: 'linear-gradient(145deg, #321e23, #201719)',
      border: '1px solid #57313a',
      borderRadius: '18px',
      padding: '18px',
      display: 'grid',
      gridTemplateColumns: '48px 1fr',
      gap: '12px',
   },
   gameIcon: {
      width: '48px',
      height: '48px',
      display: 'grid',
      placeItems: 'center',
      borderRadius: '14px',
      color: '#ffc3cf',
      backgroundColor: 'rgba(168, 71, 93, 0.28)',
   },
   gameText: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
   },
   gameButton: {
      gridColumn: '1 / -1',
      minHeight: '42px',
      borderRadius: '11px',
      color: palette.text,
      backgroundColor: palette.burgundy,
      fontWeight: 800,
      fontSize: '0.9rem',
      marginTop: '4px',
   },
   mobileNav: {
      display: 'none',
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      minHeight: '68px',
      paddingBottom: 'env(safe-area-inset-bottom, 0px)',
      backgroundColor: 'rgba(14, 13, 12, 0.96)',
      backdropFilter: 'blur(16px)',
      borderTop: `1px solid ${palette.border}`,
      zIndex: 5,
      '@media (max-width: 900px)': {
         display: 'grid',
         gridTemplateColumns: 'repeat(5, 1fr)',
      },
   },
   mobileNavButton: {
      color: palette.muted,
      minHeight: '64px',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '5px',
      fontSize: '0.7rem',
   },
   mobileNavActive: { color: palette.amber },
   playNavButton: { color: palette.text },
});
